name = "avalidurl-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

# KV namespace for Keystatic sessions
[[kv_namespaces]]
binding = "SESSION"
id = "b3f7c7a87c8b422ebfaaaac0451c7d8f"
preview_id = "5856b8e85e834ed19b0f314db8b337bb" 